---
endpoint:
  description: "S3 Bucket Server including port (example.com:9000)"
  type: "string"
  required: false
  secret: false
endpoint_secure:
  description: "Whether to use HTTPS or not for the server"
  type: boolean
  required: false
  default: true
  secret: false
access_key:
  description: "Access Key"
  type: "string"
  required: false
  secret: true
secret_key:
  description: "S3 Bucket Secret Key"
  type: "string"
  required: false
  secret: true